name: manosaba_utils
description: Anan's Sketchbook & Tachibana's Gallery for Android
publish_to: "none"
version: 1.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  share_plus: ^10.0.0
  path_provider: ^2.1.1
  gal: ^2.3.2
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  version: ^3.0.2
  permission_handler: ^12.0.1
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # 确保你把 BaseImages 文件夹和 font.ttf 复制到了项目根目录下的 assets 文件夹中
  assets:
    - assets/BaseImages/
    - assets/TachibanaImages/
    # 如果有 overlay 图片
    # - assets/BaseImages/base_overlay.png

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/font.ttf
    - family: Microsoft YaHei
      fonts:
        - asset: assets/fonts/msyh.ttc
    - family: Microsoft YaHei Bold
      fonts:
        - asset: assets/fonts/msyhbd.ttc
    - family: Microsoft YaHei Light
      fonts:
        - asset: assets/fonts/msyhl.ttc
    - family: SimHei
      fonts:
        - asset: assets/fonts/simhei.ttf
    - family: Source Han Serif SC
      fonts:
        - asset: assets/fonts/SourceHanSerifSC.otf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/BaseImages/base.png"
  min_sdk_android: 21
